PackageIdentifier: mq1.TinyWiiBackupManager
PackageVersion: 4.5.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
  - silent
UpgradeBehavior: install
ProductCode: TinyWiiBackupManager
ReleaseDate: 2025-12-01
AppsAndFeaturesEntries:
  - ProductCode: TinyWiiBackupManager
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mq1/TinyWiiBackupManager/releases/download/v4.5.1/TinyWiiBackupManager-v4.5.1-windows-x86_64-setup.exe
    InstallerSha256: 8d65afb4440b5fd359bb2d10a8c94a735c4416732352815c777b6ef5079c6420
  - Architecture: arm64
    InstallerUrl: https://github.com/mq1/TinyWiiBackupManager/releases/download/v4.5.1/TinyWiiBackupManager-v4.5.1-windows-arm64-setup.exe
    InstallerSha256: da960747100ff901502add822c441cca17cc3e9940d7f8c497dbca1a408ea95c
  - Architecture: x86
    InstallerUrl: https://github.com/mq1/TinyWiiBackupManager/releases/download/v4.5.1/TinyWiiBackupManager-v4.5.1-windows-x86-setup.exe
    InstallerSha256: 7bdfc5a8bda0c3d23aed9cadde9e6d953beaa30a8ef29131803a6ae673059513
ManifestType: installer
ManifestVersion: 1.10.0
