[target.x86_64-unknown-linux-gnu]
rustflags = ["-Z", "unstable-options", "-C", "linker-features=+lld"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Z", "unstable-options", "-C", "linker-features=+lld"]

[target.i686-unknown-linux-gnu]
rustflags = ["-Z", "unstable-options", "-C", "linker-features=+lld"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.aarch64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.i686-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-win7-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-win7-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-C", "target-feature=+crt-static"]

[env]
CC = "clang"
CXX = "clang++"
